/*
 * Membership APIs
 *
 * To search, enroll, perform benefit selection and view all the eligibile benefits
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ExtendedErrorModel : ErrorModel,  IEquatable<ExtendedErrorModel>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ExtendedErrorModel" /> class.
        /// </summary>
        /// <param name="Message">Message (required).</param>
        /// <param name="Code">Code (required).</param>
        /// <param name="RootCause">RootCause (required).</param>
        public ExtendedErrorModel(string Message = null, int? Code = null, string RootCause = null)
        {
            // to ensure "Message" is required (not null)
            if (Message == null)
            {
                throw new InvalidDataException("Message is a required property for ExtendedErrorModel and cannot be null");
            }
            else
            {
                this.Message = Message;
            }
            // to ensure "Code" is required (not null)
            if (Code == null)
            {
                throw new InvalidDataException("Code is a required property for ExtendedErrorModel and cannot be null");
            }
            else
            {
                this.Code = Code;
            }
            // to ensure "RootCause" is required (not null)
            if (RootCause == null)
            {
                throw new InvalidDataException("RootCause is a required property for ExtendedErrorModel and cannot be null");
            }
            else
            {
                this.RootCause = RootCause;
            }
            
        }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [DataMember(Name="message")]
        public string Message { get; set; }

        /// <summary>
        /// Gets or Sets Code
        /// </summary>
        [DataMember(Name="code")]
        public int? Code { get; set; }

        /// <summary>
        /// Gets or Sets RootCause
        /// </summary>
        [DataMember(Name="rootCause")]
        public string RootCause { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ExtendedErrorModel {\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  RootCause: ").Append(RootCause).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public  new string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != GetType()) return false;
            return Equals((ExtendedErrorModel)obj);
        }

        /// <summary>
        /// Returns true if ExtendedErrorModel instances are equal
        /// </summary>
        /// <param name="other">Instance of ExtendedErrorModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ExtendedErrorModel other)
        {

            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    this.Message == other.Message ||
                    this.Message != null &&
                    this.Message.Equals(other.Message)
                ) && 
                (
                    this.Code == other.Code ||
                    this.Code != null &&
                    this.Code.Equals(other.Code)
                ) && 
                (
                    this.RootCause == other.RootCause ||
                    this.RootCause != null &&
                    this.RootCause.Equals(other.RootCause)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Message != null)
                    hash = hash * 59 + this.Message.GetHashCode();
                if (this.Code != null)
                    hash = hash * 59 + this.Code.GetHashCode();
                if (this.RootCause != null)
                    hash = hash * 59 + this.RootCause.GetHashCode();
                return hash;
            }
        }

        #region Operators

        public static bool operator ==(ExtendedErrorModel left, ExtendedErrorModel right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ExtendedErrorModel left, ExtendedErrorModel right)
        {
            return !Equals(left, right);
        }

        #endregion Operators

    }
}
